name: HeldStone
main: me.heldplayer.HeldStone.HeldStone
version: 2.00
softdepend: [ Vault ]
authors: [ heldplayer ]
commands:
  heldstone:
    description: Main plugin command.
    usage: /<command> help
    aliases: [ hs, hstone ]
  trigger:
    description: Triggers a command sign
    usage: /<command> [id]
    aliases: [ t ]
permissions:
  heldstone.*:
    description: Gives complete access to HeldStone
    default: op
    children:
      heldstone.command.*: true