name: HeldStone
main: dsiwars.co.cc.HeldStone.HeldStone
version: 1.9
commands:
    heldstone:
        description: Main plugin command.
        usage: /heldstone
    hs:
        description: Main plugin command.
        usage: /hs
    trigger:
        description: Triggers a command sign
        usage: /trigger
    t:
        description: Triggers a command sign
        usage: /t
permissions:
    heldstone.*:
        description: Gives complete access to HeldStone
        children:
            heldstone.command.*: true
            heldstone.select.*: true
            heldstone.ic.*: true
            heldstone.debug: true
            heldstone.colouredSigns: true
    heldstone.command.*:
        description: Gives access to all the HeldStone commands
        children:
            heldstone.command.disable: true
            heldstone.command.help: true
            heldstone.command.msg: true
            heldstone.command.ping: true
            heldstone.command.snow: true
            heldstone.command.biome: true
            heldstone.command.ride: true
            heldstone.command.ride.exempt: true
    heldstone.command.disable:
        description: Allows you to disable HeldStone completely
        default: op
    heldstone.command.help:
        description: Allows you to use the help command
        default: true
    heldstone.command.msg:
        description: Allows you to set a message for [announce] and [broadcast] signs
        default: true
    heldstone.command.ping:
        description: Allows you to ping every loaded sign
        default: op
    heldstone.command.snow:
        description: Allows you to use the snow palcement
        default: op
    heldstone.command.biome:
        description: Allows biome changing
        default: op
    heldstone.command.ride:
        description: Allows you to ride a player
        default: op
    heldstone.command.ride.exempt:
        description: Disallows players to ride you
        default: op
    heldstone.select.*:
        description: Allowes you to select areas
        children:
            heldstone.select.cuboid: true
            heldstone.select.single: true
    heldstone.select.cuboid:
        description: Allows you to select a cuboid area
        default: true
    heldstone.select.single:
        description: Allows you to select a single block
        default: true
    heldstone.ic.*:
        description: Gives access to all the HeldStone ICs
        children:
            heldstone.ic.logic.*: true
            heldstone.ic.wireless.*: true
            heldstone.ic.set.*: true
            heldstone.ic.check.*: true
            heldstone.ic.sensor.*: true
            heldstone.ic.chat.*: true
            heldstone.ic.spawn.*: true
            heldstone.ic.functional.*: true
            heldstone.ic.shoot.*: true
    heldstone.ic.logic.*:
        description: Gives access to all the logic signs
        children:
            heldstone.ic.logic.rand: true
            heldstone.ic.logic.logic: true
            heldstone.ic.logic.delay: true
            heldstone.ic.logic.toggle: true
            heldstone.ic.logic.clock: true
            heldstone.ic.logic.trigger: true
    heldstone.ic.logic.rand:
        description: Allows you to create RAND signs
        default: true
    heldstone.ic.logic.logic:
        description: Allows you to create LOGIC signs
        default: true
    heldstone.ic.logic.delay:
        description: Allows you to create DELAY signs
        default: true
    heldstone.ic.logic.toggle:
        description: Allows you to create TOGGLE signs
        default: true
    heldstone.ic.logic.clock:
        description: Allows you to create CLOCK signs
        default: true
    heldstone.ic.logic.trigger:
        description: Allows you to create TRIGGER signs
        default: true
    heldstone.ic.wireless.*:
        description: Gives access to all the wireless signs
        children:
            heldstone.ic.wireless.send: true
            heldstone.ic.wireless.recv: true
    heldstone.ic.wireless.send:
        description: Allows you to create SEND signs
        default: true
    heldstone.ic.wireless.recv:
        description: Allows you to create RECV signs
        default: true
    heldstone.ic.set.*:
        description: Gives access to all the set signs
        children:
            heldstone.ic.set.stime: true
            heldstone.ic.set.sweather: true
    heldstone.ic.set.stime:
        description: Allows you to create STIME signs
        default: op
    heldstone.ic.set.sweather:
        description: Allows you to create SWEATHER signs
        default: op
    heldstone.ic.check.*:
        description: Gives access to all the check signs
        children:
            heldstone.ic.check.ctime: true
            heldstone.ic.check.cweather: true
    heldstone.ic.check.ctime:
        description: Allows you to create CTIME signs
        default: true
    heldstone.ic.check.cweather:
        description: Allows you to create CWEATHER signs
        default: true
    heldstone.ic.sensor.*:
        description: Gives access to all the sensor signs
        children:
            heldstone.ic.sensor.logged: true
            heldstone.ic.sensor.sensor: true
            heldstone.ic.sensor.psensor: true
            heldstone.ic.sensor.isensor: true
            heldstone.ic.sensor.msensor: true
            heldstone.ic.sensor.wasensor: true
            heldstone.ic.sensor.lasensor: true
            heldstone.ic.sensor.lisensor: true
            heldstone.ic.sensor.players: true
    heldstone.ic.sensor.logged:
        description: Allows you to create LOGGED signs
        default: true
    heldstone.ic.sensor.sensor:
        description: Allows you to create SENSOR signs
        default: true
    heldstone.ic.sensor.psensor:
        description: Allows you to create PSENSOR signs
        default: true
    heldstone.ic.sensor.isensor:
        description: Allows you to create ISENSOR signs
        default: true
    heldstone.ic.sensor.msensor:
        description: Allows you to create MSENSOR signs
        default: true
    heldstone.ic.sensor.wasensor:
        description: Allows you to create WSENSOR signs
        default: true
    heldstone.ic.sensor.lasensor:
        description: Allows you to create LSENSOR signs
        default: true
    heldstone.ic.sensor.lisensor:
        description: Allows you to create LSENSOR signs
        default: true
    heldstone.ic.sensor.players:
        description: Allows you to create PLAYERS signs
        default: true
    heldstone.ic.chat.*:
        description: Gives access to all the chat signs
        children:
            heldstone.ic.chat.disp: true
            heldstone.ic.chat.announce: true
            heldstone.ic.chat.glannounce: true
    heldstone.ic.chat.disp:
        description: Allows you to create DISP signs
        default: true
    heldstone.ic.chat.announce:
        description: Allows you to create ANNOUNCE signs
        default: true
    heldstone.ic.chat.glannounce:
        description: Allows you to create GLANNOUNCE signs
        default: op
    heldstone.ic.spawn.*:
        description: Gives access to all the spawn signs
        children:
            heldstone.ic.spawn.cuboid: true
            heldstone.ic.spawn.spawn: true
            heldstone.ic.spawn.item: true
    heldstone.ic.spawn.cuboid:
        description: Allows you to create CUBOID signs
        default: op
    heldstone.ic.spawn.spawn:
        description: Allows you to create SPAWN signs
        default: op
    heldstone.ic.spawn.item:
        description: Allows you to create ITEM signs
        default: op
    heldstone.ic.functional.*:
        description: Gives access to all the functional signs
        children:
            heldstone.ic.functional.bolt: true
            heldstone.ic.functional.cauldron: true
            heldstone.ic.functional.effect: true
            heldstone.ic.functional.blackhole: true
            heldstone.ic.functional.areatoggle: true
    heldstone.ic.functional.bolt:
        description: Allows you to create BOLT signs
        default: true
    heldstone.ic.functional.cauldron:
        description: Allows you to create CAULDRON signs
        default: true
    heldstone.ic.functional.effect:
        description: Allows you to create EFFECT signs
        default: true
    heldstone.ic.functional.blackhole:
        description: Allows you to create BLACKHOLE signs
        default: op
    heldstone.ic.functional.areatoggle:
        description: Allows you to create AreaToggle signs
        default: op
    heldstone.ic.shoot.*:
        description: Gives access to all the functional signs
        children:
            heldstone.ic.shoot.snowball: true
            heldstone.ic.shoot.explball: true
    heldstone.ic.shoot.snowball:
        description: Allows you to create SNOWBALL signs
        true: op
    heldstone.ic.shoot.explball:
        description: Allows you to create ExplBall signs
        true: op
    heldstone.debug:
        description: Allows you to get debug info
        default: op
    heldstone.colouredSigns:
        description: Allows you to create coloured signs
        default: op